### ISSUE TITLE
JWE support

### ISSUE THREAD

**Issue by boyand** [keycloak/keycloak-gatekeeper#125]
Hey, 

First of all great work on the keycloak proxy. Looks pretty good! 

A current use case we have is supporting JWE as we do not want to send plain JWTs to the clients in every case. Keycloak currently does not support this. What are your thoughts on configurable JWE support within the proxy. The scenario is basically to encrypt the tokens before being sent to the clients.

**Comment by gambol99** [comment]
Admittedly they would be a fairy big change, as I don't believe the go-oidc lib i'm using supports JWE, I'd probably have to move to https://github.com/square/go-jose. Though i'm happy to take a look

**Comment by mozesmagyar** [comment]
Has this been done? It looks like [your own](https://github.com/gambol99/go-oidc) oidc implementation supports JWE. I'm also running into the same desire for the proxy to support encryption, which it seems to do but then for me it fails to decrypt the token, which makes some sense to me as keycloak itself doesn't natively support encrypted tokens.

**Comment by abstractj** [comment]
@boyand @mozesmagyar thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
