### ISSUE TITLE
More TLS options

### ISSUE THREAD

**Issue by allandegnan** [keycloak/keycloak-gatekeeper#195]
Expose more TLS options such as acceptable ciphers and protocols.

**Comment by abstractj** [comment]
@allandegnan thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
