### ISSUE TITLE
Access Token shouldn't be subject to same claims validation as ID token

### ISSUE THREAD

**Issue by Cobi** [keycloak/keycloak-gatekeeper#229]
Here, you attempt to validate the access token:
https://github.com/gambol99/keycloak-proxy/blob/master/handlers.go#L178

But you pass it into `go-oidc`'s ID token verification process:
https://github.com/gambol99/keycloak-proxy/blob/master/oauth.go#L49

Which expects an IDToken:
https://github.com/coreos/go-oidc/blob/fe7346e2e6855bda769d5b3db7d917f159c5613c/oidc/client.go#L787

And so it verifies the claims on the token:
https://github.com/coreos/go-oidc/blob/master/oidc/verification.go#L167

Which checks, among other things, the audience:
https://github.com/coreos/go-oidc/blob/master/oidc/verification.go#L120

Which is not required on the Access Token by the OIDC spec, just on the IDToken:
http://openid.net/specs/openid-connect-basic-1_0.html#IDTokenValidation

**Comment by gambol99** [comment]
hi @Cobi .. if memory recalls the logic was; default to the ID Token and only if there's an access token use that. I believe it was because the access token used by Google was not a JWT. Moving forward though [go-oidc](https://github.com/coreos/go-oidc) appears to permit skipping this in [#PR129](https://github.com/coreos/go-oidc/pull/129)

**Comment by logophobia** [comment]
Pretty sure I'm having the same issue, it's blocking using the client credentials flow.

curl.exe -X POST -d "client_id=client&client_secret=secret&grant_type=client_credentials" http://localhost/connect/token

curl.exe --header "Authorization: Bearer eyJhbGciOiJSUzI1Ni....." ...

error   no session found in request, redirecting for authorization      {"error": "missing required claim: sub"}

**Comment by abstractj** [comment]
@Cobi @logophobia thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
