### ISSUE TITLE
/oauth endpoints only respond to GET but authorization middleware can direct to them with other methods

### ISSUE THREAD

**Issue by martin-watts** [keycloak/keycloak-gatekeeper#292]
I think this is right, but happy to be corrected: 

The oauth/authorization is added to the route in sever.go (ln 189):
```golang
        e.Get(authorizationURL, r.oauthAuthorizationHandler)
```

This is only responding to GET requests, but the authorization middleware responds to all methods.

The problem:

The authorization middleware calls ```redirectToAuthorization``` (misc.go) for a variety of reasons (middleware.go#authenticationMiddleware)

If redirection is configured, ```redirectToAuthorization``` calls ```redirectToURL```

```golang
        r.redirectToURL(oauthURL+authorizationURL+authQuery, w, req)
``` 

Which redirects the request with the status ```http.StatusTemporaryRedirect``` (307). 
307 tells the user agent that the target resource has temporarily moved, and - if it performs an automatic redirect - to perform the same request at the temporary location using the same method as the original request. 

If the proxy is protecting a website that uses basic HTTP forms, and (e.g.) the user's session times out, and the next action they perform is a form submit (POST) this results in the browser redirecting to: 

    POST /oauth/authorization?state=abc

Which doesn't work as nothing is listening for it. 

I _think_ a more appropriate redirect code would be ```http.StatusSeeOther``` (303) as most (all?) user agents will see that code and perform a GET to the redirect url; unless there's a compelling reason to leave it as 307?

Possibly make it configurable?

**Comment by gambol99** [comment]
hi @martin-watts ... apologizes for the delay on this one, been on a long Christmas break ... Taking a look at this one now ...

**Comment by pjeby** [comment]
#### Data Loss

In order not to break the underlying app, it'd probably be best not to redirect at all, but offer a 403 error page asking the user to log in again using a different tab or window, then reload the current window.  Otherwise the form data will be lost.  This would probably need to be a custom page, like the login page.

Redirecting would result in there being no way to recover the data they entered on the form prior to POSTing it, as in many cases going back to the form page would lose the data.

#### Workarounds

Currently, the best way to mitigate this issue is to use refresh tokens with a relatively long life, so that redirecting to the IdP isn't required during normal user activity.  If you're using the default settings of both Keycloak and this proxy, users will be redirected every 5 minutes; if you enable refresh tokens, then as long as a user doesn't idle for more than 30 minutes, they shouldn't be redirected.  The refresh token lifetime can also be increased in Keycloak's realm settings under "Tokens", "SSO Session Idle".

In addition, you can keep a user logged in by having an iframe containing a page served through the proxy that periodically refreshes itself: literally it can just be a protected HTML page with a meta refresh so it reloads.  Then the redirect is done to the page in the iframe, which is a harmless GET, and the session stays logged in.

**Comment by martin-watts** [comment]
Thanks @pjeby, I agree with your points. 

We're currently working around the issue with long lived refresh tokens, but it's not ideal from a security p.o.v. RE: The refreshing page in an iframe - I can see the merits in it in terms of UX - but it would stretch the definition of the session becoming 'idle', as it'd keep the session alive without user interaction. It would allow shorter token lifetimes though which is probably a good trade-off. 

I'm not overly concerned with losing user input, as the forms are pretty small (a few fields), and this should really be an edge-case rather than frequent behaviour. 

That said, I accept that your proposals could be better options for a lot of users.

**Comment by DoomGerbil** [comment]
My PR was just merged in that addresses this.  With this change, you can now pass in the flag/config option `invalid-auth-redirects-with-303` to change this behavior to use a `303 See Other` redirect code instead of the default `307 Temporary Redirect`.  This will allow those of us who are OK with losing any POST/PUT data to redirect to auth using a 303, which will force the use of a GET, and thus successfully re-auth.

**Comment by abstractj** [comment]
@martin-watts closing this, because it was fied in @DoomGerbil's PR. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
