### ISSUE TITLE
URLs are urlencoded in outgoing requests

### ISSUE THREAD

**Issue by bogbert** [keycloak/keycloak-gatekeeper#305]
Hi,
I'm not sure if it's a bug or if it's done on purpose, but I noticed that the URLs are urlencoded in keycloak-proxy outgoing requests.
For example, for an incoming request containing a pipe in the URL like this one:

```
POST /blahblah/foo|bar HTTP/1.1
[...]
```

the outgoing request is:

```
POST /blahblah/foo%7Cbar HTTP/1.1
[...]
```

**Comment by abstractj** [comment]
@bogbert thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
