### ISSUE TITLE
Dynamic configuration via API?

### ISSUE THREAD

**Issue by ror6ax** [keycloak/keycloak-gatekeeper#309]
Hi. This project is really awesome, thanks for your work!

Have you considered exposing API to make configuration dynamic? I can't possibly know the upstream urls and other parameters in advance in my case.

I'm willing to whip up a PR if you are ok with adding this.

Thanks

**Comment by gambol99** [comment]
hi @ror6ax ... i was thinking about doing something similar at one point based around keycloak's implementation of UMA but back then the router was gin and dynamic changes weren't supported. Though a PR is always welcome :-)

**Comment by ror6ax** [comment]
Happily. Have you seen the specs for UMA 2.0, by the way? What design API design do you have in mind?

**Comment by abstractj** [comment]
@ror6ax thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
