### ISSUE TITLE
Insufficient entropy in state parameter

### ISSUE THREAD

**Issue by lsthornt** [keycloak/keycloak-gatekeeper#317]
I'm using keycloak-proxy with [Hydra](https://github.com/ory/hydra) backend, and running into an issue with the `?state=` query parameter. Hydra requires the the state to be at least 8 characters [[link]](https://github.com/ory/fosite/blob/831f56a9e6774b1e80c13cd301583edea6378245/authorize_request_handler.go#L75), which causes problems when keycloak-proxy proxies paths less than 4 characters due to base64 encoding [[link]](https://github.com/gambol99/keycloak-proxy/blob/master/misc.go#L99).

Would you accept a pull request that adds a short prefix (e.g. `path_`) to the pre-encoded bytes, in order to increase the entropy in that parameter?

**Comment by abstractj** [comment]
@lsthornt thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
