### ISSUE TITLE
Can't logout, because incorrect implementation of logoutHandler

### ISSUE THREAD

**Issue by jangaraj** [keycloak/keycloak-gatekeeper#360]
[logoutHandler](https://github.com/gambol99/keycloak-proxy/blob/ab5ef860694f75238419f135ab0e0d60f897002d/handlers.go#L277-L385) doesn't use right parameters and request type for logout endpoint - [openid specification](http://openid.net/specs/openid-connect-session-1_0.html#RPLogout).

I've received error from my IdP (it's not a Keycloak):
```
1.5268947352571363e+09  error   invalid response from revocation endpoint       {"status": 405, "response": "{\"message\":\"Request method 'POST' not supported\"}"}
```

Apparently, keycloak-proxy sends POST request:
```
request, err := http.NewRequest(http.MethodPost, revocationURL, bytes.NewBufferString(fmt.Sprintf("refresh_token=%s", identityToken)))
```
but GET logout request is expected:
```
curl -X GET "<end_session_endpoint>?\
&state=<state>\
&id_token_hint=<id-token>\
&post_logout_redirect_uri=<redirect_uri>"
```

**Comment by abstractj** [comment]
@jangaraj thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
