### ISSUE TITLE
Timeout waiting for headers

### ISSUE THREAD

**Issue by markwimpory** [keycloak/keycloak-gatekeeper#382]
Resolved in 2.2.0.

2.1.1 will intermittently fail as the updstream header timeout default setting is only 1 second.  This can be overridden in config.

**Comment by abstractj** [comment]
@markwimpory I'm closing it, because it seems like your issue was already resolved. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
