### ISSUE TITLE
Support for dex's custom claims

### ISSUE THREAD

**Issue by kron4eg** [keycloak/keycloak-gatekeeper#413]
Hello, what an awesome tool you've developed here, thanks a lot!

Now to the issue: at the moment keycloak-proxy is unable to verify hashmap claims, like dex is issuing with `--scopes=federated:id`, that will result claim like this:

```
"federated_claims": {
  "connector_id": "github",
  "user_id": "110272483197731336751"
}
```

dex documentation: https://github.com/coreos/dex/blob/master/Documentation/custom-scopes-claims-clients.md#custom-claims
keycloak-proxy sources: https://github.com/gambol99/keycloak-proxy/blob/master/middleware.go#L244-L273

**Comment by jangaraj** [comment]
Brainstorming: maybe the implementation of optional `jsonpath` syntax will solve all complex queries. For example:
```
match-claims:
  $.federated_claim.connector_id: github
```

**Comment by kron4eg** [comment]
that'd be awesome!

**Comment by abstractj** [comment]
@kron4eg thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
