### ISSUE TITLE
Turn keycloak-proxy into Kubernetes Ingress Controller CRD

### ISSUE THREAD

**Issue by styk-tv** [keycloak/keycloak-gatekeeper#414]
admission into various back-end service endpoints **should happen based on standard kubernetes ingress (kind) annotations**, similar to what swagger is doing with [openapi3 implementation](https://swagger.io/docs/specification/authentication/openid-connect-discovery/) but on the ingress proxy level.

this might happen in a separate repo, however backlog pipeline should have this item visible as it represents a large interest group from k8s community and is currently a much missed element.

**Comment by abstractj** [comment]
@styk-tv thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
