### ISSUE TITLE
require-any-role is not supported on the CLI

### ISSUE THREAD

**Issue by andyflatt** [keycloak/keycloak-gatekeeper#424]
Get the error message 

```
[error] invalid resource uri=/*|roles=integration:admin,integration:user|require-any-role: true, invalid resource keypair, should be (uri|roles|methods|white-listed)=comma_values
```

Looks like this field needs to be added to the validation message
https://github.com/keycloak/keycloak-gatekeeper/blob/master/resource.go#L39

**Comment by gambol99** [comment]
hi @andyflatt ... you sure this isn't a typo i.e. `require-any-role: true` should be `require-any-role=true` .. Though error message should be updated ..

**Comment by abstractj** [comment]
@andyflatt thanks for taking your time reporting this. The repository keycloak-proxy was moved to Keycloak organization and renamed to keycloak-gatekeeper. If you still think this issue is valid, please read https://www.keycloak.org/community.html and report your bug/feature request to https://issues.jboss.org/browse/KEYCLOAK.
