### ISSUE TITLE
Gatekeeper Ajax calls unauthorized 307

### ISSUE THREAD

**Issue by abstractj** [keycloak/keycloak-gatekeeper#578]
## What: 

  I am currently implementing Gatekeeper instead of Proxy to protect certain applications.
  
  I am working on Graylog and RabbitMQ. Both systems use XMLHttpRequests (ajax) to fetch information / test login.
  I use the following configuration:
  {code:java}
      discovery-url: https://url
      client-id: id
      client-secret: secret
      listen: 0.0.0.0:8080
      upstream-url: http://app_url
      resources:
      - uri: /*
        roles:
        - monitoring
  {code}
  When the apps POST an ajax call to /api/session to try to login, it gatekeeper returns a 307 and redirects the call to KeyCloak, which is not allowed becouse of CORS, which is correct. 
  All the assets like /img/styles.css do work. So I think it is only in ajax calls.

## Reference:

- [KEYCLOAK-9099 - Gatekeeper Ajax calls unauthorized 307](https://issues.redhat.com/browse/KEYCLOAK-9099)

**Comment by gboor** [comment]
I think this one is already fixed. You can set up a gatekeeper instance with `no-redirects: true`, which will then return 401s instead of 307s on auth failure.

**Comment by abstractj** [comment]
Thanks @gboor that helps. Closing it.

**Comment by sankarp-kavach** [comment]
@abstractj @gboor I came here from https://issues.redhat.com/browse/KEYCLOAK-9099 I am not sure how disabling redirect will solve the problem here. Consider the following scenario.

1) An application is deployed in http://app.example fronted by gatekeeper
2) The gatekeeper on first visit to the url, detects no session and redirects to the keycloak login page
3) Now after logging in, the same url is hit again by the browser, with the updated cookies.
4) The webapp also has a AJAX client which makes a lot of http POST calls.
5) Things work fine, smooth, until the cookies session is timedout.
6) Now the POST call by the AJAX client would fail with a `307`. But POST on the above call fails.

Now if we disable redirects in teh gatekeeper, how will the above problem be solved ? Wouldn't the application be not failing in step2 itself ?

**Comment by gboor** [comment]
@sankarp-kavach that indeed would require a per-url config for this setting. I don't run into this issue, because my front-ends and back-ends are always separate.

@abstractj I don't know if this is in scope at all, but it might be worth reopening the ticket if there are any future plans for something like this. One option might be to detect AJAX headers, though that would not work for gRPC requests. That is how https://github.com/oauth2-proxy/oauth2-proxy does it, apparently.
